name = "apis-do"
route = { pattern = "*/*", zone_name = "apis.do" }
main = "worker.js"
usage_model = "unbound"
compatibility_date = "2022-09-23"

services = [
  { binding = "CTX", service = "ctx-do", environment = "production" }
]
