on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nathanclevenger/esbuild-http-import-action@v1
        with:
          entryPoint: "./pkg/index.ts"
          outfile: "./pkg/dist/index.js"
      - uses: JS-DevTools/npm-publish@v1
        with:
          package: ./pkg/package.json
          token: ${{ secrets.NPM_TOKEN }}
